SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SH_BLOCK_INFO] (
		[TABLENAME]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CURRENT_BLOCK]     [int] NOT NULL,
		[MAX_BLOCK]         [int] NOT NULL,
		CONSTRAINT [PK__SH_BLOCK__36580732109769F5]
		PRIMARY KEY
		CLUSTERED
		([TABLENAME])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SH_BLOCK_INFO] SET (LOCK_ESCALATION = TABLE)
GO
